namespace FDCApp.Contracts.Constants
{
    public static class ConfigConstant
    {
        public const string Display_Date_Format = "MM/dd/yyyy";
        public const string Display_Time_Format = "hh':'mm tt";
        public readonly static string Display_DateTime_Format = $"{Display_Date_Format} {Display_Time_Format}";
        public const string Display_Value_Format = "0.##";
        public const string Zero_Acceptable_Range = "0.05";

        public const int Download_Chunck_Amount = 6;
        public const int Upload_Chunck_Amount = 5;

        public const double HttpRequest_Timeout_Minutes = 4;
        public const double Gps_Timeout_Seconds = 5;

        public const int Retry_Max_Attempts_Number = 3;
        public const int Retry_Paused_Seconds = 2;

        public const int Max_Days_Number = 30;

        public const int Valid_Radio_Button_Answers = 3;

        public const string Forms_Create_Default_Text = "Add New Inspection";

        public const string Autogenerated_DefaultValue = "AUTO-{{" + KeywordConstants.Epoch + "}}";
    }
}