namespace FDCApp.Contracts.Constants
{
    public class ErrorCodes
    {
        //Forms
        public const string AnswerOptions_InvalidNumber_NewForm = "AO1";
        public const string AnswerOptions_InvalidNumber_EditForm = "AO2";
        public const string Autogenerated_InvalidKeyword = "AUTO";
        public const string GpsCoordinates_Disabled = "ERR-GPSCOORD-1";
        public const string GpsCoordinates_NotGranted = "ERR-GPSCOORD-2";
        public const string FormList_InvalidConfiguration = "ERR-FL-{0}";
    }
}
